[tool.black]
line-length = 100
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
    | .git
    | .venv
    | build
    | dist
)
'''

[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true